# This file is a template, and might need editing before it works on your project.
# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: blang/latex

build:
  script:
    - latexmk -pdf
  artifacts:
    paths:
      - "*.pdf"

pages:
  stage: deploy
  script:
    - mkdir public  # create a folder called public
    - cp main.pdf public  # copy the pdf file into the public folder
  artifacts:
    paths: 
      - public  # instruct GitLab to keep the public folder
  only: 
    - master  # deploy the pdf only for commits made to the master branch 
